annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Add GPG provenance signing for Helm repo
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: EE19FA216B8349AC017C5279B4C062080CDC2061C264EE92CF98300E39FD40A8
    url: https://kubelauncher.github.io/charts/cosign.pub
apiVersion: v2
appVersion: 2.6.12
description: OpenLDAP directory service
home: https://github.com/kubelauncher/charts
icon: https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/openldap.svg
keywords:
- openldap
- ldap
- directory
maintainers:
- email: platform@kubelauncher.com
  name: kubelauncher
  url: https://www.kubelauncher.com
name: openldap
sources:
- https://github.com/kubelauncher/docker
- https://github.com/kubelauncher/charts
type: application
version: 0.1.8
