FROM kubelauncher/openldap:2.6.12

USER root

RUN mkdir -p /data/openldap/config /data/openldap/data /data/openldap/run && chown -R 1001:root /data/openldap && chmod 770 /data/openldap/config /data/openldap/data
